### ISSUE TITLE
Issue installing

### ISSUE THREAD

**Issue by Overload119** [facebook/homebrew-fb#10]
==> ./build.sh fbsimctl build /usr/local/Cellar/fbsimctl/HEAD-2c37d34
Last 15 lines from /Users/asharifr/Library/Logs/Homebrew/fbsimctl/01.build.sh:

*\* BUILD FAILED **

The following build commands failed:
    CompileSwift normal x86_64 /tmp/fbsimctl-20160929-51632-e7cz30/fbsimctl/FBSimulatorControlKit/Sources/CLIBootstrapper.swift
    CompileSwift normal x86_64 /tmp/fbsimctl-20160929-51632-e7cz30/fbsimctl/FBSimulatorControlKit/Sources/CommandBuffer.swift
    CompileSwift normal x86_64 /tmp/fbsimctl-20160929-51632-e7cz30/fbsimctl/FBSimulatorControlKit/Sources/Arguments.swift
    CompileSwift normal x86_64 /tmp/fbsimctl-20160929-51632-e7cz30/fbsimctl/FBSimulatorControlKit/Sources/Environment.swift
    CompileSwift normal x86_64 /tmp/fbsimctl-20160929-51632-e7cz30/fbsimctl/FBSimulatorControlKit/Sources/DeviceReporter.swift
    CompileSwift normal x86_64 /tmp/fbsimctl-20160929-51632-e7cz30/fbsimctl/FBSimulatorControlKit/Sources/Subjects.swift
    CompileSwift normal x86_64 /tmp/fbsimctl-20160929-51632-e7cz30/fbsimctl/FBSimulatorControlKit/Sources/Defaults.swift
    CompileSwift normal x86_64 /tmp/fbsimctl-20160929-51632-e7cz30/fbsimctl/FBSimulatorControlKit/Sources/iOSReporter.swift
    CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(9 failures)

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/facebook/homebrew-fb/issues

**Comment by sdwilsh** [comment]
You are probably better off raising this on the fbsimctl project.  This is a collection of Facebook projects in one homebrew package, and that project is likely to be able to help you moreso than here.

**Comment by Coneko** [comment]
Here's the project: https://github.com/facebook/FBSimulatorControl
