### ISSUE TITLE
idb-companion.rb should have branch set to main

### ISSUE THREAD

**Issue by sheldonneuberger-sc** [facebook/homebrew-fb#67]
idb-companion.rb doesn't have a branch specified so it defaults to master, it should be "main" though.

**Comment by sheldonneuberger-sc** [comment]
The CLA signing process is unfortunately tedious in my company, I can't re-open the PR. I also don't know how to test this fix.

**Comment by sheldonneuberger-sc** [comment]
`head "https://github.com/facebook/idb.git", branch: "main"` is the correct fix btw.

**Comment by Ashoat** [comment]
I am seeing this issue too. My CLA is signed and I've submitted #71 to resolve.

**Comment by KapJI** [comment]
Closed by https://github.com/facebook/homebrew-fb/pull/71.
