### ISSUE TITLE
Unable to "brew install folly" on Yosemite

### ISSUE THREAD

**Issue by abhi18av** [facebook/homebrew-fb#8]
Hii homebrew-fb team)

I'm unable to install the [Facebook's Folly C++ library ](https://github.com/facebook/folly) as a brew formula, even though all dependencies have been met.

<img width="1440" alt="screen shot 2016-09-20 at 6 22 58 pm" src="https://cloud.githubusercontent.com/assets/12799326/18670955/cba04d16-7f5f-11e6-8b1e-d990f770aede.png">
<img width="1440" alt="screen shot 2016-09-20 at 6 23 06 pm" src="https://cloud.githubusercontent.com/assets/12799326/18670961/d0126adc-7f5f-11e6-80fd-bc474832dc17.png">

**Comment by Coneko** [comment]
The error says you need macOS El Capitan or newer.

See the wiki page for mappings of names to version numbers so you can compare them easily: https://en.wikipedia.org/wiki/OS_X .

**Comment by sdwilsh** [comment]
The folly recipe isn't part of this repo, either.  You might be better off filing it in facebook/folly instead :)

**Comment by abhi18av** [comment]
Oh, boy! That much...

Well, Okay thanks for the directions anyway.
